import React, { useEffect, useState, useMemo } from 'react';
import { Search, Users, Scale } from 'lucide-react';
import PageSkeleton from '../components/LoadingSkeleton/PageSkeleton';
import { Pagination } from '../components/ProjectFilters';

export default function Ipr() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [search, setSearch] = useState('');
  const [roleFilter, setRoleFilter] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);

  const SHEET_URL = 'https://opensheet.elk.sh/14Xz-Gg74ERDRkFMT_ocq0NWsnRwMDUFSBb8ooZSduiQ/Sheet1';

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const res = await fetch(SHEET_URL);
        if (!res.ok) {
          throw new Error(`HTTP ${res.status}: The Google Sheet may not be publicly shared`);
        }
        const json = await res.json();
        const items = (Array.isArray(json) ? json : []).map((d, idx) => ({
          id: idx,
          sl_no: d['sl_no'] ?? idx + 1,
          Name: d['name'] ?? d['Name'] ?? '',
          current: d['current'] ?? '',
          role: d['role'] ?? ''
        }));
        setData(items);
      } catch (err) {
        console.error('Failed to fetch IPR committee data', err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  // Extract unique roles
  const roles = useMemo(() => {
    return [...new Set(data.map(item => item.role).filter(Boolean))].sort();
  }, [data]);

  // Filter data
  const processedData = useMemo(() => {
    let filtered = [...data];

    if (search.length >= 2) {
      const searchLower = search.toLowerCase();
      filtered = filtered.filter(item =>
        (item.Name?.toLowerCase() || '').includes(searchLower) ||
        (item.current?.toLowerCase() || '').includes(searchLower)
      );
    }

    if (roleFilter !== 'all') {
      filtered = filtered.filter(item => item.role === roleFilter);
    }

    return filtered;
  }, [data, search, roleFilter]);

  // Pagination
  const totalPages = Math.ceil(processedData.length / itemsPerPage);
  const paginatedData = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return processedData.slice(start, start + itemsPerPage);
  }, [processedData, currentPage, itemsPerPage]);

  // Reset page on filter change
  useEffect(() => {
    setCurrentPage(1);
  }, [search, roleFilter, itemsPerPage]);

  if (loading) return <PageSkeleton />;

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 p-4 flex flex-col items-center justify-center">
        <div className="text-center text-red-600 p-6 bg-red-50 rounded-lg max-w-lg">
          <p className="font-semibold text-xl">Error loading data</p>
          <p className="text-sm mt-2">{error}</p>
          <p className="text-xs mt-4 text-gray-500">
            Make sure the Google Sheet is shared publicly (Anyone with the link can view)
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-[95%] mx-auto p-4" id="ipr-top">
      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-4xl md:text-6xl font-bold text-gray-800 flex items-center justify-center gap-3">
          <Scale className="text-purple-700" size={36} />
          IPR Policy Review Committee
        </h1>
        <p className="text-gray-600 mt-3 text-base md:text-lg max-w-3xl mx-auto">
          The Committee for Intellectual Property Policy Review ensures comprehensive 
          and structured revision of the Institute's IP policy.
        </p>
      </div>

      {/* Description */}
      <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-8">
        <p className="text-gray-700">
          The existing Intellectual Property (IP) policy of IIT Dharwad plays a crucial role in
          safeguarding and managing innovations, research outcomes, and intellectual assets
          generated by faculty, students, and staff. With evolving research landscapes,
          emerging technologies, and changing regulatory frameworks, it is essential to
          periodically review and update the IP policy.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div className="bg-white rounded-lg shadow-md border border-gray-200 p-5 md:p-6">
          <div className="flex items-center gap-3">
            <Users className="text-purple-600" size={24} />
            <div>
              <p className="text-base md:text-lg text-gray-600 font-medium">Committee Members</p>
              <p className="text-3xl font-bold text-gray-800">{data.length}</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md border border-gray-200 p-5 md:p-6">
          <div className="flex items-center gap-3">
            <Scale className="text-purple-600" size={24} />
            <div>
              <p className="text-base md:text-lg text-gray-600 font-medium">Unique Roles</p>
              <p className="text-3xl font-bold text-purple-600">{roles.length}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Search */}
      <div className="relative mb-4">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
        <input
          type="text"
          placeholder="Search by name or faculty..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
        />
      </div>

      {/* Filters */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4 mb-6">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-600 mb-1">Role</label>
            <select
              value={roleFilter}
              onChange={(e) => setRoleFilter(e.target.value)}
              className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
            >
              <option value="all">All Roles</option>
              {roles.map((role, idx) => (
                <option key={idx} value={role}>{role}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-600 mb-1">Show per page</label>
            <select
              value={itemsPerPage}
              onChange={(e) => setItemsPerPage(Number(e.target.value))}
              className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
            >
              <option value={5}>5</option>
              <option value={10}>10</option>
              <option value={25}>25</option>
              <option value={50}>50</option>
            </select>
          </div>

          <div className="flex items-end">
            <p className="text-sm text-gray-600 pb-2">
              Showing {processedData.length} of {data.length} members
            </p>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto shadow-lg rounded-lg">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-purple-800">
            <tr>
              <th className="px-4 py-3.5 text-left text-sm md:text-base font-semibold text-white">S.No</th>
              <th className="px-4 py-3.5 text-left text-sm md:text-base font-semibold text-white">Name</th>
              <th className="px-4 py-3.5 text-left text-sm md:text-base font-semibold text-white">Faculty</th>
              <th className="px-4 py-3.5 text-left text-sm md:text-base font-semibold text-white">Role</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {paginatedData.length === 0 ? (
              <tr>
                <td colSpan="4" className="px-4 py-8 text-center text-gray-500">
                  No members found matching your criteria.
                </td>
              </tr>
            ) : (
              paginatedData.map((item) => (
                <tr key={item.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 text-sm font-medium text-gray-900">{item.sl_no}</td>
                  <td className="px-4 py-3 text-sm font-medium text-gray-900">{item.Name}</td>
                  <td className="px-4 py-3 text-sm text-gray-700">{item.current}</td>
                  <td className="px-4 py-3 text-sm text-gray-700">
                    <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${
                      item.role === 'Chairperson' || item.role === 'Chairman' ? 'bg-purple-100 text-purple-700' :
                      item.role === 'Convener' || item.role === 'Member Secretary' ? 'bg-green-100 text-green-700' :
                      'bg-gray-100 text-gray-700'
                    }`}>
                      {item.role}
                    </span>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      <Pagination
        currentPage={currentPage}
        totalPages={totalPages}
        onPageChange={setCurrentPage}
        totalItems={processedData.length}
        itemsPerPage={itemsPerPage}
      />
    </div>
  );
}
